# Generated by Django 5.1 on 2024-09-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cloud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("AWS", "Amazon Web Service"),
                            ("GCP", "Google Cloud Provider"),
                            ("Azure", "Microsoft Azure"),
                        ],
                        max_length=10,
                    ),
                ),
                ("access_key", models.CharField(max_length=100)),
                ("secret_key", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("endpoint", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            ("RUNNING", "running"),
                            ("STOPPED", "stopped"),
                            ("DEPROVISIONING", "deprovisioning"),
                            ("DEPROVISION_FAILED", "deprovisioning_failed"),
                            ("PROVISIONING", "provisioning"),
                            ("PROVISION_FAILED", "provisioning_failed"),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "cloud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="portal.cloud"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="portal.cluster"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
